version: "3"  

tasks:
  default:
    cmds:
      - task: server

  server:
    cmds:
      - cmd: go run ./cmd/server {{.CLI_ARGS}}
        ignore_error: true

  client:
    cmds:
      - cmd: go run ./cmd/client {{.CLI_ARGS}}

  build:
    cmds:
      - cmd: go build -o ./bin/keeper ./cmd/client